export const LANDING_REQUEST = "LANDING_REQUEST";
export const LANDING_SUCCESS = "LANDING_SUCCESS";
export const LANDING_FAIL = "LANDING_FAIL";

export const SUBJECT_REQUEST = "SUBJECT_REQUEST";
export const SUBJECT_SUCCESS = "SUBJECT_SUCCESS";
export const SUBJECT_FAIL = "SUBJECT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const PAGE_REQUEST = "PAGE_REQUEST";
export const PAGE_SUCCESS = "PAGE_SUCCESS";
export const PAGE_FAIL = "PAGE_FAIL";

export const NEW_FILE_REQUEST = "NEW_FILE_REQUEST";
export const NEW_FILE_SUCCESS = "NEW_FILE_SUCCESS";
export const NEW_FILE_FAIL = "NEW_FILE_FAIL";

export const NEW_FILE_RESET= "NEW_FILE_RESET";

export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAIL = "LIKE_FAIL";

export const SUBJECT= "SUBJECT";

export const ME_REQUEST = "ME_REQUEST";
export const ME_SUCCESS = "ME_SUCCESS";
export const ME_FAIL = "ME_FAIL";
export const CLEAR_LIKES = "CLEAR_LIKES";
export const DELETE_FILE_REQUEST = "DELETE_FILE_REQUEST";
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
export const DELETE_FILE_FAIL = "DELETE_FILE_FAIL";
export const ALLKEYS_REQUEST = "ALLKEYS_REQUEST";
export const ALLKEYS_SUCCESS = "ALLKEYS_SUCCESS";
export const ALLKEYS_FAIL = "ALLKEYS_FAIL";

export const ACCEPT_REQUEST = "ACCEPT_REQUEST";
export const ACCEPT_SUCCESS = "ACCEPT_SUCCESS";
export const ACCEPT_FAIL = "ACCEPT_FAIL";

export const REJECT_REQUEST = "REJECT_REQUEST";
export const REJECT_SUCCESS = "REJECT_SUCCESS";
export const REJECT_FAIL = "REJECT_FAIL";

export const ADMIN_DELETE_REQUEST = "ADMIN_DELETE_REQUEST";
export const ADMIN_DELETE_SUCCESS = "ADMIN_DELETE_SUCCESS";
export const ADMIN_DELETE_FAIL = "ADMIN_DELETE_FAIL";




